os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: oYlJpTDqEdgF88465FeQbPH1v1NloUBxmMuzo4TtSR99oAaGqSUh1Kz17cGkpuOymVeFWJxpCT+az8U0aQNXA0jzaiMQhf69UUPDLCEpMPq35O+vazseKEMVWMRrfnBECGcUnkoVIAeo5ws90keK3eCT+7EfdN72+8yYRAQ7aYF5sdWCcmpxfDygEML574/C3+7ntwGHF5CTudPwCO8Z/an2M7dmjKBDtGnBnVtf3KH4qillyfNJEv6p0VlN/VXFnehRnqI8E56all+W2rmckXNiB94S+G7fJIMgPnQBuaW4QP1DjvpsVOtFZUIS2AzM0fEGmsXeDCeEMPcjaE+OdwOyAylMePEkOEbHRz+IIBhd7vRytvtQkFqGiBoZJd6FouGlkhpc5mKt2n8JCC0d9g0Y53ZNGZhWoojDR8AQ47Q9PeXw6/bDCU0XoSrzEjBL+bB+aBaQNwlXzjJfN1VXAKdeg53QZIr5Ovv/B/aXYyhMe9cuphyXp8E6oV+dtkMj9Yow3Hf2Uf0UgVtYZs5y7GJ9ZFE+DfBGkQjVTtA/GoWrWJfQOofMYHbGdwGukRV8CF5QVwDniz1mZBhUpTWHzk9VvnZTAy+WHUuenr0hWZMzMCSEV/huK3TBgK93pZ2U8ygOGHwvFOBHr/VmHMh9Pfk08LG/Yz1dBp36HS79ZpQ=
