os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: ExssORaiEl0sre+N1xLbl2fLlCNjQq+FowYQGwhhU2zl6Y473U88U+biMV0XeZyjG6AE/oegRofaqpUH0YBVN4SOfassw+eisHmJbnHhBTbeFvaU/RrQw0WEQwYLNLfV4DuOZeCh7Fes4U7eZEc6QOG6m5x/rA7EtLoA/g3XdOt77IsLdrT6ofNc6C5N7lSAt97ox0aniZJxAJ95gNXwWV37OjdMRr9mSa1j23U5qBF2WXkHklGrZvwbr0+VMi1MIsv+h2n6evDzafeWolETPDeOLaBd8fWkVzVt4TSPshV2lIwf4+YuLU2qD6vmtpbiWMZ51RikvJDrXa10vf9TulGRyJZU07+KaZg6ZA5a36HAf82HtpGmM7RejO6h78WFgy49NzwtxCDxYk8snTPDeI+0X45W3Ufl1NyqipGZYej1Qpn+FYzNgVOElucxGAEUFvtuqmFQgbe66AsOc40fzp8s+rlc0fUW4erewDCrdYQnOKWzDeh6r6JiptDSdkYgvM0VUlTfyCL247xkOJvGWTmKQ2mJrGLV8t1waKPD05yGumjL5d7Tt85FWJVhfAozT0h07fuCOusghXAKrQNAse9gxzWzcggVcR0ztlaISyrDYNfbiGcHxW/Zr8f5nB9DhR8ngEKbPSBvXj7t63VL+RKwqdUAM2YFjVSxXdUo6Hk=
